### ISSUE TITLE
Cannot Find module 'electron'

### ISSUE THREAD

**Issue by ThamerMalki** [enginestein/Reversecord#3]
I cloned the project and was trying to run the 'index.js' file in "\app" folder but it throws an error

```
node:internal/modules/cjs/loader:1078
  throw err;
  ^
Error: Cannot find module 'electron'
```
not sure if it's some Dependency error or what.

**Comment by ThamerMalki** [comment]
I think 'electron' module doesn't exist so I installed it, but still nothing works.

**Comment by enginestein** [comment]
You won't be able to run it like this. This code is just decryption of discord's code, reverse engineered. It provides the code but not the method to build it. When I have time, I will surely look at it and find some way to compile it.
